server:
  port: 80
  servlet:
    session:
      timeout: 1m

dutlzn:
  security:
    authentication:
      loginPage: /login/page
      loginProcessingUrl: /login/form
      usernameParameter: name
      passwordParameter: pwd
      staticPaths:
        - /dist/**
        - /modules/**
        - /plugins/**
      loginType: REDIRECT

spring:
  thymeleaf:
    cache: false
  datasource:
    username: root
    password: yourpassword
    url: jdbc:mysql://47.98.209.48:3306/study-security?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    # mysql8版本以上驱动包指定新驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
